### PR TITLE
[RFC] refactor: switch to `got` as http client library

### PR DESCRIPTION
**Pull request by raymondfeng**
## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by bajtos** [comment]
What is the motivation for this change? Are there any known problems with `axios`? Are there any notable features provided by `got` but not available in `axios`?

My primary requirement for an http client is to preserve stack traces of low-level Node.js errors thrown e.g. when TLS handshake or proxy connection setup fails. Historically, many modern clients were wrapping Node.js errors into custom error instances described in Fetch specification, which made troubleshooting pretty impossible.

`axios` fixed that problem long time ago. I checked `got` sources and it looks like they are most likely not wrapping low-level errors any more, but I am not sure. Can you please double check?

Assuming that `got` is preserving original error stack traces, I am fine start using it, **as long as we use it consistently everywhere**. I really don't want to end up with the situation where some of LoopBack packages are using axios and other are using got.

**Comment by raymondfeng** [comment]
I'm still struggling with `packages/http-caching-proxy` to use `got`, which does not have built-in proxy support.

**Comment by bajtos** [comment]
> I'm still struggling with `packages/http-caching-proxy` to use `got`, which does not have built-in proxy support.

I have encountered similar troubles in the past too. Can you perhaps check how is axios implementing proxy support?

**Review by bajtos — APPROVED** [review]
I guess it's better to use `got` in at least few places rather than stick to `request` everywhere.

Can you @raymondfeng please update `got` to the latest version and rebase this pull request on top of the latest `master`, to ensure all is still good?

**Pull request closed without merging**
