### PR TITLE
fix: lerna has not correctly generated the package-lock-json

### PR DESCRIPTION
**Pull request by frbuceta**

### CODE REVIEW

**Review by achrinza — CHANGES_REQUESTED** [review]
suggestion: describe the fix instead of the problem in the Git Commit Subject.

Broken lockfiles are also don't prevent use of the packages as they're not published, hence `chore:` may be more appropriate.

```
chore: regenerate lockfiles

Regenerate lockfiles that were broken by Lerna
```

**Comment by frbuceta** [comment]
> 

The latest version is breaking due to package-locks. If you try to install a new project it fails.

**Comment by frbuceta** [comment]
Doing `npm i --force` fixes trying to install the new release

**Comment by achrinza** [comment]
@frbuceta Could we start a discussion on this with the other maintainers? It doesn't make sense as `package-lock.json` never gets published to NPM and is ignored if found in a dependency.

**Pull request closed without merging**
