### PR TITLE
feat(cli): add prefix to openapi generator

### LINKED ISSUE #9328: lb4 openapi doesn't work with openapi specs generated by loopback itself
### Describe the bug

The `lb4 openapi` command fails to generate working code in case the specification provided is generated by loopback. This shouldn't be the case as the specification is generated by LoopBack and the framework uses that same spec.

To reproduce this, generate specs from any lb4-based project. Then use that same specification to generate openapi artifacts with lb4 `openapi`. The resulting app creates buggy code.

### Logs

```shell
src/models/index.ts:2:1 - error TS2308: Module './account-with-relations.model' has already exported a member named 'AccountWithRelations'. Consider explicitly re-exporting to resolve the ambiguity.

2 export * from './account.model';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/models/index.ts:6:1 - error TS2308: Module './customer-with-relations.model' has already exported a member named 'CustomerWithRelations'. Consider explicitly re-exporting to resolve the ambiguity.

6 export * from './customer.model';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Additional information

_No response_

### Reproduction

https://github.com/aaqilniz/lb4-ex-openapi

### PR DESCRIPTION
**Pull request by aaqilniz**
The `lb4 openapi` generator doesn't work if the openapi specification is generated by LoopBack itself due to duplication of artifacts. 

This PR enables lb4 openapi to accept an option `prefix` to rename routes and artifacts with a prefix. If no prefix is provided, the default is set to `openapi` - ensuring no conflict happens. It also enables to generate artifacts from more than one spec at the same time.

Fixes #9328 

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by aaqilniz** [comment]
Hi, @samarpanB and @dhmlau can you please have a look at the PR?

**Review by samarpanB — CHANGES_REQUESTED** [review]
I believe we should try to find the root cause of this issue first. Having a prefix is a good feature but many a times users may not like it. So I think we should find the root cause of why duplicate entries are there in open api schema generated by loopback in first place.

**Comment by aaqilniz** [comment]
Hi, @samarpanB. Thanks a lot for the review & the feedback. 

As you said, a prefix is a good feature in itself. This would enable the loopback-next user to generate APIs from multiple openapi specifications. And yes, someone might not want any prefixes to the original specs. We can make the prefix optional (currently its default value is openapi - so a prefix is added even if the user doesn't provide it).

And about the duplication, if you have a look at the openapi specs, you'll see it generates separate schemas for `<model>WithRelations`, `new<Model>`, and so on. This results in duplication as the `<model>WithRelations` is already being exported by the model schema itself.

image
image
image

**Comment by aaqilniz** [comment]
Hi, @dhmlau. Can you have a look at the PR?

**Comment by aaqilniz** [comment]
Closing the PR in favor of [PR#10350](https://github.com/loopbackio/loopback-next/pull/10350)

**Pull request closed without merging**
