### PR TITLE
ci: remove AppVeyor in favour of the Windows runner

### PR DESCRIPTION
**Pull request by frbuceta**

### CODE REVIEW

**Comment by frbuceta** [comment]
Any rejection of this PR? @loopbackio/loopback-maintainers

**Review by dhmlau — APPROVED** [review]
sounds good to me. Thanks @frbuceta.

**Comment by frbuceta** [comment]
> sounds good to me. Thanks @frbuceta.

Thank you for helping me to pass this PR. The next step is to convert the monorepo into a workspace to minimise waiting time and adapt to Lerna v7.

**Comment by frbuceta** [comment]
@dhmlau Do you have sufficient permissions to remove AppVeyor from the integrations of this repository?

**Pull request merged**
