### PR TITLE
fix: add authorization missing components and configs to documentation

### PR DESCRIPTION
**Pull request by albjeremias**
## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

I was following the guide: 

https://loopback.io/doc/en/lb4/Authorization-component-authorizer.html

and had been verrry frustated... but then i found this:

https://stackoverflow.com/questions/64369657/loopback-4-authorization-provider-not-working

and I wondered.. why isn't this in the documentation??!

### CODE REVIEW

**Comment by dhmlau** [comment]
@albjeremias, thanks for the PR. I looked through the link you provided and also https://github.com/loopbackio/loopback-next/issues/6580, your changes LGTM. Before merging this PR, could you please take care of the following:
- sign the DCO. See https://loopback.io/doc/en/contrib/code-contrib.html for details. 
- make sure the commit message adheres to [our commit message guideline](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#commit-message-guidelines). One suggestion would be:   `fix(docs): <your original commit msg>` 

Thanks!

**Comment by albjeremias** [comment]
> @albjeremias, thanks for the PR. I looked through the link you provided and also #6580, your changes LGTM. Before merging this PR, could you please take care of the following:
> 
>     * sign the DCO. See https://loopback.io/doc/en/contrib/code-contrib.html for details.
> 
>     * make sure the commit message adheres to [our commit message guideline](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#commit-message-guidelines). One suggestion would be:   `fix(docs): <your original commit msg>`
> 
> 
> Thanks!

Thank you! :) I'm very pleased to support back. 
I have no idea how-to search or how-to edit a pushed commit. do i create another  PR?! about the DCO, i will do it when i known how-to the other fix!

If there is a place to add a loopback projet.. we are now developing this:
 https://github.com/helpbuttons/hb-back/

**Comment by dhmlau** [comment]
@albjeremias 
> I have no idea how-to search or how-to edit a pushed commit. do i create another PR?! about the DCO, i will do it when i known how-to the other fix!

You can amend the commit, in that case, there's no need to create a new PR. If you're using the CLI, you can:
- check out your branch `albjeremias:fix-authorizer-docs`
- run `git commit --amend -s` . Then follow the prompt to edit the commit message. Also by adding the `-s` option, it signs the commit. 

Hope it helps.

> If there is a place to add a loopback projet.. we are now developing this:
https://github.com/helpbuttons/hb-back/

Will take a look at your project soon. Thank you for your support.

**Comment by albjeremias** [comment]
i couldn't ammend.. here a new PR: https://github.com/loopbackio/loopback-next/pull/7945 im closing this one

**Pull request closed without merging**
