### PR TITLE
Typo: possessive instead of plural?

### PR DESCRIPTION
**Pull request by dfberry**
fix(docs): change plural to possessive for applications.

## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]
@dfberry, thanks for catching this!

**Comment by dhmlau** [comment]
@dfberry, could you please fix the commit linting error? 
My suggested commit message would be as below, but feel free to change it. Thanks.
```
fix(docs): change plural to possessive for applications.
```

**Comment by dfberry** [comment]
@dhmlau I changed it but not sure if the change is correct.

**Comment by dhmlau** [comment]
@dfberry, hm.. it doesn't look like so, unfortunately. If you're using GitHub cli, you can edit the commit message by using the following command:
```
$ git commit --amend 
```

Then follow the prompt to edit. After it's done, run:
```
$ git push --force-with-lease
```

If it still doesn't work, I can help you to edit as well.

**Review by achrinza — APPROVED** [review]
Thaksin for catching that, @dfberry!

As per-@dhmlau's comment, we just need the commit message to be updated  such that it follows Semantic Commits. The steps provided should work just fine.

If you prefer, we can also edit the commit from our end as well.

**Pull request closed without merging**
