### PR TITLE
chore: reuse license spec compliance

### PR DESCRIPTION
**Pull request by achrinza**
see https://reuse.software

Signed-off-by: Rifa Achrinza <25147899+achrinza@users.noreply.github.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by NorthDecoder — COMMENTED** [review]
This is the first that I have heard of REUSE, so I am not really qualified to make an authoritative statement, so please take this as more of an edification question.  I copy and pasted the api.reuse link to see the result for looback-next and it found thousands of noncompliant files!

1. Do you really want a failed status badge at the top of the readme?
2. How will a license be embedded in files like json?

**Comment by achrinza** [comment]
Thanks for the questions, I'm more than happy to clarify;

> Do you really want a failed status badge at the top of the readme?

The badge is based off the default `master` branch, which does not have `.reuse/dep5` yet (It's in this commit).

This commit also adds a "REUSE Lint" GitHub Action, which does the same check against the merge commit. If the GitHub Action passes, the REUSE API would also pass after merge.

From experience, the badge will update itself as "compliant" after merging this PR after several minutes.

> How will a license be embedded in files like json?

For such files, the [REUSE spec](https://reuse.software/spec/) states to either have a `<original filename>.license` file with the necessary headers OR a `.reuse/dep5` file. I've decided on the latter as its easier to have a single file for a large repo like LoopBack 4 instead of a bunch of `.license` files.

**Review by bajtos — CHANGES_REQUESTED** [review]
Thank you @achrinza for the pull request. I'd like you to clarify few aspects of the proposed changes:

- Why do we need `LICENSES/MIT.txt`, when there is already `LICENSE` file with (mostly) the same content?
- We are already following https://spdx.dev standard for licenses. Is it really necessary to support REUSE too?

I'd like to hear from @dhmlau and @raymondfeng too, since license-related changes are potentially tricky.

**Comment by bajtos** [comment]
> We are already following https://spdx.dev standard for licenses. Is it really necessary to support REUSE too?

Found some info here: https://reuse.software/comparison/

> SPDX is the rock upon which REUSE is built. SPDX defines a standardized way to share copyright and licensing information between projects and people. Read more in [our FAQ](https://reuse.software/faq/#what-is-spdx)

**Comment by dhmlau** [comment]
I would also second @bajtos's opinion on https://github.com/strongloop/loopback-next/pull/7018#pullrequestreview-571294352. Lacking the knowledge on REUSE, I guess the other way to put the question would be what's the benefit of adopting REUSE if it seems like we already cover a similar license. Thanks.

**Pull request closed without merging**
