### PR TITLE
fix: enable the lb4 repository accept repositoryBaseClass option

### PR DESCRIPTION
**Pull request by aaqilniz**
Currently, the lb4 repository fails to set repositoryBaseClass based on provided option in the configs. This PR will enable the lb4 repository to update the repositoryBaseClass with the value provided in the configs.

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

### CODE REVIEW

**Review by samarpanB — CHANGES_REQUESTED** [review]
Can you please add some test case for this ?

**Comment by aaqilniz** [comment]
Hello, @samarpanB thanks for the review. I've added a test case for the scenario. Please have a look.

**Review by samarpanB — APPROVED** [review]

**Review by samarpanB — CHANGES_REQUESTED** [review]
Can you check whether your test case covers the changed line ? it seems it doesn't.

**Comment by aaqilniz** [comment]
Hi @samarpanB. Please have a look at the test now. Let me know if we still need any change before merging this PR.

**Comment by aaqilniz** [comment]
Hi, @achrinza  Please have a look at this PR too, and provide your feedback.

**Comment by samarpanB** [comment]
@aaqilniz Please check why the checks are failing.

**Comment by samarpanB** [comment]
@aaqilniz one check is still failing. Would you please check ?

**Comment by aaqilniz** [comment]
Hi, @achrinza, can you please have a look at the PR?

**Comment by aaqilniz** [comment]
Hi, @dhmlau, can you please review the PR?

**Comment by aaqilniz** [comment]
Hi, @achrinza and @dhmlau. Can you please review the PR and suggest to me any changes needed?

**Comment by aaqilniz** [comment]
Hi, @achrinza & @dhmlau. Can you please have a look at the PR whenever you've the change?

**Comment by aaqilniz** [comment]
Hi, @achrinza. Can you please have a look at the PR?

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@aaqilniz, your changes LGTM. Since there are 2 approvals already, so i'm going to land this PR.

**Pull request merged**
