### PR TITLE
fix(docs): middleware sequence document update

### PR DESCRIPTION
**Pull request by vaibhavkumar-sf**
middleware sequence document update for typo from middlware to middleware

Signed-off-by: Vaibhav Kumar <vaibhav.kumar@sourcefuse.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by achrinza** [comment]
Same issue; package.json downgrade changes are included in the commit

**Comment by vaibhavkumar-sf** [comment]
@achrinza , no there is no change in package.json in this commit .. should I rebase with master again ?

**Comment by achrinza** [comment]
Just noticed that as well; Yes, let's try to rebase against the latest master.

**Comment by vaibhavkumar-sf** [comment]
Ok @achrinza , rebasing my all branches with MASTER again

**Comment by vaibhavkumar-sf** [comment]
@achrinza , please check this particular PR again, is it fine now ? I've rebased with latest master branch, If fine then I'll do same process with my other branches too

**Comment by achrinza** [comment]
Yup, the diff now show the correct changes

**Review by achrinza — APPROVED** [review]

**Pull request merged**
