### PR TITLE
fix(cli): correct generated typescript type for MySQL Binary template…

### PR DESCRIPTION
**Pull request by trmaphi**
… type (https://github.com/strongloop/loopback-next/issues/6295)

## Checklist

- [X] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by bajtos** [comment]
@jannyHou can you please take a look? I am not sure if the pull request is fixing the right place.

@trmaphi can you please add a test to verify the fix and prevent regressions in the future?

**Comment by bajtos** [comment]
Quoting from #6295:

```ts
  @property({
    type: 'Binary',
    required: true,
    length: 65535,
    mysql: {columnName: 'photo', dataType: 'blob', dataLength: 65535, dataPrecision: null, dataScale: null, nullable: 'N'},
  })
```

I was not aware that `Binary` is a valid property type and wanted to proposed to fix the type conversion in loopback-connector-mysql? See https://github.com/strongloop/loopback-connector-mysql/blob/c681b2dbe72b4cf9e75ccc7016f1fc2e8ef6cd1d/lib/discovery.js#L334-L339, but then I discovered that other connectors are using `Binary` type too - see e.g. https://github.com/strongloop/loopback-connector-postgresql/blob/ced6c286f7baffaf8f569af747d943d0da96ffa4/lib/discovery.js#L341-L342, so it looks like `Binary` is indeed a valid type :+1:

When adding support for a new property type, it would be great to update other places to recognize the new type too.
- We have a type class for buffers in [`packages/repository/src/types/buffer.ts`](https://github.com/strongloop/loopback-next/blob/4bc457f7d4f8be1ff099bcec435db3a4d03850ca/packages/repository/src/types/buffer.ts). I am not sure how are these classes used or registered, it would be great to implement an alias for `Binary` that would use `BufferType` under the hood.
- The code building JSON/OpenAPI schema needs to convert `Binary` to proper schema type. I found only this place dealing with `buffer` type, I am not sure if that's the only one to fix: https://github.com/strongloop/loopback-next/blob/4bc457f7d4f8be1ff099bcec435db3a4d03850ca/packages/repository-json-schema/src/build-schema.ts#L227-L230

  Considering that  #6295 is dealing with model properties only, I think we should focus on this use case. How are binary properties converted to JSON now? In LoopBack 3, we use Node.js' built-in `Buffer.prototype.toJSON` function that returns a value like `{ type: 'Buffer', data: [50, 51] }`. This rather inefficient and probably difficult to describe via JSON/OpenAPI schema. See https://github.com/strongloop/loopback/issues/1907 for more details.

It looks that supporting Binary properties at REST layer is rather tricky, I guess it's best to leave that out of scope of this pull request?

In that case we can keep the scope of this pull request to fix `createPropertyTemplateData` only, but please do include a test to verify the fix. I think [`packages/cli/test/unit/discover/import-discovered-model.test.js`](https://github.com/strongloop/loopback-next/blob/4bc457f7d4f8be1ff099bcec435db3a4d03850ca/packages/cli/test/unit/discover/import-discovered-model.test.js) is a good place where to add such test(s).

**Review by jannyHou — COMMENTED** [review]
@trmaphi Thank you for taking care of this PR! 
And appreciate the details from @bajtos, yes I think for this PR, let's add a test in https://github.com/strongloop/loopback-next/blob/4bc457f7d4f8be1ff099bcec435db3a4d03850ca/packages/cli/test/unit/discover/import-discovered-model.test.js to verify it.

**Comment by jannyHou** [comment]
cc @trmaphi any update on this PR? Let me know if you have any questions :)

**Pull request closed without merging**
