### PR TITLE
chore: update package locks

### PR DESCRIPTION
**Pull request by dhmlau**
Ran `npm run update-package-locks` to update the package lock files. 

cc @samarpanB 

## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by samarpanB** [comment]
Some tests failing. Not sure if those are due to this change or not.

**Comment by frbuceta** [comment]
I have not seen this PR. I have merge a commit that fixes the update problem but it gives a problem in the Sequelize extension.

**Comment by frbuceta** [comment]
It's failing here

https://github.com/loopbackio/loopback-next/blob/c9c35c9f422a8621571fc089af4e5e3b69d16979/extensions/sequelize/src/sequelize/sequelize.repository.base.ts#L274

It is a method of Sequelize. See https://sequelize.org/docs/v6/core-concepts/model-querying-finders/#findbypk

**Comment by frbuceta** [comment]
I have found the problem. Sequelize creates a column of type array in INTEGER. That is what is giving problems.

https://github.com/loopbackio/loopback-next/blob/c9c35c9f422a8621571fc089af4e5e3b69d16979/extensions/sequelize/src/sequelize/sequelize.repository.base.ts#L765-L771

image

**Comment by samarpan-b** [comment]
I have asked @shubhamp-sf to check it.

**Comment by shubhamp-sf** [comment]
@frbuceta It's actually the underlying package (sqlite3) upgrade in this PR that caused this issue.

I've also reported the same on their repo, please go through the issue summary here: https://github.com/TryGhost/node-sqlite3/issues/1694

I had reported this to @dhmlau in this renovate PR: https://github.com/loopbackio/loopback-next/pull/9367#issuecomment-1495305098

cc: @samarpan-b

**Comment by shubhamp-sf** [comment]
Just raised a fix to use the working version of sqlite3 statically (until it gets fixed in the upstream) https://github.com/loopbackio/loopback-next/pull/9547


Also Diana, @frbuceta already pushed the [lock maintenance 3 days back](https://github.com/loopbackio/loopback-next/commit/c9c35c9f422a8621571fc089af4e5e3b69d16979). Doesn't it already includes the changes this PR addresses?

**Comment by samarpanB** [comment]
@dhmlau after this PR - https://github.com/loopbackio/loopback-next/pull/9547, tests are now passing. I think this PR is not needed anymore.

**Comment by dhmlau** [comment]
@samarpanB @shubhamp-sf, should we close this PR then?

**Pull request closed without merging**
