### PR TITLE
fix(docs): Adding loopback4-starter

### PR DESCRIPTION
**Pull request by mbnoimi**
## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [X] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
@mbnoimi, thanks for the PR. Could you please take care of the following: 
- fix the commit message linter issue. 
    - Please see the [commit message guidelines](https://loopback.io/doc/en/lb4/code-contrib-lb4.html#commit-message-guidelines)
- sign the DCO
    - you can do so by running `git commit --amend -s`. For more info, see https://loopback.io/doc/en/contrib/code-contrib.html#signing-off-commits-using-dco. 

Thanks.

**Comment by dhmlau** [comment]
cc @samarpanB

**Review by samarpan-b — APPROVED** [review]

**Review by samarpanB — APPROVED** [review]

**Comment by dhmlau** [comment]
@mbnoimi, would you be able to fix the issues mentioned in https://github.com/strongloop/loopback-next/issues/7105#issuecomment-786807984? Thanks.

**Comment by dhmlau** [comment]
@mbnoimi, ping again. Just wondering if you'd be able to sign the DCO for the PR as the minimum, where I can take care of fixing the commit message? Without signing the DCO, I'm afraid that I cannot accept your PR. 

Since this PR has been idle for more than a month, I'd like to wait for a week before closing it as abandoned. Thanks.

**Pull request closed without merging**
