### PR TITLE
fix(cli): allow belongsTo relation with same table

### PR DESCRIPTION
**Pull request by aaqilniz**
This PR will allow belongsTo relations with the same table.
Currently creating relations with the same table results in buggy code.

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [x] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by aaqilniz** [comment]
All of the tests pass locally. Not sure why they are failing here.

**Comment by aaqilniz** [comment]
Please have a look at this PR too whenever you get a chance, @samarpanB.

**Review by achrinza — APPROVED** [review]
Changes LGTM 👍 

Just need to fix code lint issue before merging - Would reverting the eslintrc change fix the problem?

**Comment by aaqilniz** [comment]
The eslintrc change I've made is due to another error happening at my local setup. It throws the following error when I am trying to commit the changes. 

```Oops! Something went wrong! :(

ESLint: 8.26.0

Error: .eslintrc.js » ./packages/eslint-config/eslintrc.js:
	Configuration for rule "@typescript-eslint/prefer-nullish-coalescing" is invalid:
	Value {"allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing":true} should NOT have additional properties.```

**Comment by aaqilniz** [comment]
This condition was added in [this](https://github.com/loopbackio/loopback-next/pull/9110/commits/dee05544943191e80e0ac817405188547473fa64) commit. This shouldn't be causing any trouble having this option fails when I try committing the code.

@achrinza any suggestion on how should I proceed?

**Comment by aaqilniz** [comment]
Hi @samarpanB. Can you help me with this PR too?

**Comment by aaqilniz** [comment]
Hi @achrinza. The linting issues are fixed and all checks have been cleared too. Please have a look and let me know if the PR can be merged now.

**Comment by aaqilniz** [comment]
Hi @achrinza  @samarpanB @raymondfeng . Please have a look at the PR and let me know if it can get merged.

**Review by samarpanB — APPROVED** [review]

**Comment by samarpanB** [comment]
Looks good to me. Thank you for the contribution @aaqilniz . Merging it now.

**Pull request merged**
