### PR TITLE
fix(sequelize): fix column name selection for belongsTo relation

### PR DESCRIPTION
**Pull request by KalleV**
Fixes: #9591

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by samarpanB — APPROVED** [review]
LGTM. @KalleV can you please run prettier fix to resolve the code linter check ? Thats the only thing blocking it.

**Comment by samarpanB** [comment]
@KalleV can you please check the lint issue ? Thats the only issue pending on this PR.

**Comment by vaibhavkumar-sf** [comment]
@samarpanB  subscribed to it :)

**Comment by samarpanB** [comment]
Added a new PR adding more test cases here - https://github.com/loopbackio/loopback-next/pull/10008.

As this is a blocker for some of the community members, so I added a new PR using the same fix from here. Co-author is added as @KalleV .

**Comment by samarpanB** [comment]
Closing this in favour of #10008

**Pull request closed without merging**
