### PR TITLE
docs(migration-overview): fix link to 'Migrating datasources'

### PR DESCRIPTION
**Pull request by ddsultan**
Signed-off-by: ddsultan <2477698+ddsultan@users.noreply.github.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Review by achrinza — APPROVED** [review]
Thanks for the fix, @ddsultan!

Just a minor fix - Could you update the Git Commit Subject to the following?

```
fix(docs): update `Migrating datasources` dead link
```

Doesn't have to be exactly above, just needs to be `fix` type with the optional `docs` scope.

**Comment by ddsultan** [comment]
> Thanks for the fix, @ddsultan!
> 
> Just a minor fix - Could you update the Git Commit Subject to the following?
> 
> ```
> fix(docs): update `Migrating datasources` dead link
> ```
> 
> Doesn't have to be exactly above, just needs to be `fix` type with the optional `docs` scope.

@achrinza, 

Done.

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
The change LGTM. I'm not sure how we can kick off CI again besides pushing changes again. @achrinza, ideas?

**Comment by achrinza** [comment]
> I'm not sure how we can kick off CI again besides pushing changes again. @achrinza, ideas?

I don't think there's any way to manually trigger the CI for a PR.

But there was a previously-successful run (with the exception of the `Commit Lint`): https://github.com/loopbackio/loopback-next/runs/5677848458?check_suite_focus=true

If we look under on of the `Run actions/checkout@v3` job steps, we can get the commit hash for that run and cross-check with this PR to confirm that the changes were identical:

https://github.com/loopbackio/loopback-next/compare/master...b406d95e9f8be1283801bc66c28d6bdb91c00ba4

The commit lint also passes locally on my machine:

```sh
$ npm exec --no-install --package=@commitlint/cli -- commitlint --from=origin/master --to=HEAD --verbose
⧗   input: fix(docs): update 'Migrating datasources' dead link
✔   found 0 problems, 0 warnings
```

So it be safe to merge without the CI.

**Comment by dhmlau** [comment]
Thanks @achrinza. Force merging.

**Comment by dhmlau** [comment]
Thanks @ddsultan for your contribution. Your PR has landed! 🎉

**Pull request merged**
