### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MattRiddell**
TOKEN_SECRET doesn't exist on RefreshTokenServiceBindings. I assume it's supposed to be REFRESH_SECRET as that does exist.

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]

**Comment by dhmlau** [comment]
@MattRiddell, thanks for catching this. Could you please sign the DCO? Thanks. 
As a reference, please see https://loopback.io/doc/en/contrib/code-contrib.html.

**Comment by MattRiddell** [comment]
I pushed a commit with sign off, can you confirm you can see it?

**Comment by dhmlau** [comment]
@MattRiddell, hm.. it doesn't look like it's been pushed (at least it's not showing in the history of this PR). 

For DCO check, you can also look at the checks.... the DCO check is towards the bottom of the list. 
Screen Shot 2021-03-13 at 9 15 54 PM

**Comment by MattRiddell** [comment]
Not sure what's happening. The commits say they've been signed off above but it's still saying it failed DCO check.

**Comment by achrinza** [comment]
> The commits say they've been signed off above but it's still saying it failed DCO check.

There seems to be a confusion between [signing commits](https://docs.github.com/en/github/authenticating-to-github/signing-commits) with GPG, and [signing off](https://wiki.linuxfoundation.org/dco) commits with `Signed-off-by: Full Name <email>` in the Git commit message footer.

Signing off commits are done using `-s` or `--signoff`.

**Comment by MattRiddell** [comment]
The commits all had "signed off by" as does the single one above

**Comment by achrinza** [comment]
I'm able to see the sign-off now;

Just need to squash it into a single commit and tidy the commit message to comply with the Conventional Commits:

```
fix(docs): fixed refresh token secret binding key

Signed-off-by: Matthew Riddell <matt@createoffshorecompany.com>
```


image

**Pull request closed without merging**
