### PR TITLE
perf(repository): handle cloneDeep while manipulating data 

### PR DESCRIPTION
**Pull request by mlakdawala-sf**
For huge data responses was able to see a lot of spikes in flame chart which pointed at clone deep fn in repository package, after further inspection was able to handle it through an if check 

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [X] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [ ] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by mlakdawala-sf** [comment]
@nabdelgadir i ran tests on local and they were passing, can we you look into this, i profiled and was able to narrow down to this clone deep which wad not needed until we add include so this check is for that, if you have any comments or doubts please let me know

Thanks

**Comment by samarpan-b** [comment]
@achrinza do you think we can merge this ?

**Comment by achrinza** [comment]
Hi @samarpan-b, wool take a look at this in the next few days

**Comment by achrinza** [comment]
Hi @mlakdawala-sf @samarpan-b, really sorry for the delay on reviewing PRs; I've managed to get the tests to pass. Could you amend the Git commit to use either a real email or [GitHub's `noreply` email](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#about-commit-email-addresses) for the sign-off? Other than that, the PR is good to merge.

**Comment by mlakdawala-sf** [comment]
> @achrinza

Done @achrinza

**Comment by mlakdawala-sf** [comment]
Can this be merged now @achrinza

**Comment by mlakdawala-sf** [comment]
@achrinza if all good can we merge this

**Review by samarpanB — APPROVED** [review]

**Review by achrinza — APPROVED** [review]
LGTM 👍 

Can be merged after DCO/checks are resolved.

**Pull request merged**
