### PR TITLE
Fix award-winning broken link

### PR DESCRIPTION
**Pull request by joaothallis**
## Checklist

- [ ] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
@joaothallis, thanks for the PR. I'm looking into why the jekyll server cannot start properly on strongloop.com. Once that is revived, we probably don't need this change. Thanks.

**Comment by joaothallis** [comment]
> @joaothallis, thanks for the PR. I'm looking into why the jekyll server cannot start properly on strongloop.com. Once that is revived, we probably don't need this change. Thanks.

I'll close this PR then. It is the repo with the jekyll server for strongloop.com? https://github.com/strongloop/strongloop.com2? If it's is it I can take a look, I have a experience with jekyll

**Comment by dhmlau** [comment]
@joaothallis, that would be great. thanks! 
Yes, it's https://github.com/strongloop/strongloop.com2. After my [last PR ](https://github.com/strongloop/strongloop.com2/pull/1), i was able to launch the site locally. But for some reason, it does not work as a public site.

**Comment by achrinza** [comment]
Just to give an update here as well, the strongloop.com website is now back online

**Pull request closed without merging**
