### PR TITLE
feat(docs): generate Jekyll friendly pages for README files

### PR DESCRIPTION
**Pull request by raymondfeng**
This PR automates generation of pages from README files.

Screen Shot 2019-12-04 at 10 40 45 PM

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-next) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by derdeka** [comment]
+1 for doing the same for `changelog` ;-)

**Comment by raymondfeng** [comment]
> +1 for doing the same for changelog ;-)

Are you proposing to have an aggregated CHANGELOG.md?

**Comment by raymondfeng** [comment]
I created https://github.com/strongloop/loopback-next/pull/4259 to expose READMEs  to `loopback.io` site:

- docs/site/Authentication-passport.md:layout: readme
- docs/site/Metrics.md:layout: readme
- docs/site/Health.md:layout: readme 

This PR is a follow-up to #4259 to automate README to Jekyll conversion so that we have READMEs in one place.

**Comment by derdeka** [comment]
> Are you proposing to have an aggregated CHANGELOG.md?

Currently changelogs are hard to read and need a lot of research over the different packages. Personally i read the changelog by reviewing the release commit, e.g. https://github.com/strongloop/loopback-next/commit/89eb61bacaed75e6eb61ae6840cea266cb888659 . One way to optimize that is an aggregated CHANGELOG.md. But also linking the existing changelogs on one place as you do it for readme could be helpful for new developers.

**Comment by bajtos** [comment]
> > Are you proposing to have an aggregated CHANGELOG.md?
> 
> Currently changelogs are hard to read and need a lot of research over the different packages. Personally i read the changelog by reviewing the release commit, e.g. 89eb61b . One way to optimize that is an aggregated CHANGELOG.md. But also linking the existing changelogs on one place as you do it for readme could be helpful for new developers.

@derdeka can you please open a new issue to discuss this idea? I agree the current changelogs can be improved, but I feel such discussion is off-topic in this pull request.

**Comment by bajtos** [comment]
> This PR is a follow-up to #4259 to automate README to Jekyll conversion so that we have READMEs in one place.

I don't see how you are implementing the part "we have READMEs in one place". Please explain.

As I understand your proposal, some of the READMEs will be exposed at multiple URLs (in multiple places). I find that confusing.

**Comment by achrinza** [comment]
The [Authentication](https://loopback.io/doc/en/lb4/Loopback-component-authentication.html) and [Authorization](https://loopback.io/doc/en/lb4/Loopback-component-authorization.html) pages already have a similar setup. Hence with this in mind, it might be reasonable to expose the READMEs from multiple links of the sidebar so long as they are the same URL.

**Pull request closed without merging**
