### PR TITLE
fix(docs): documentation update for non-global interceptor

### PR DESCRIPTION
**Pull request by vaibhavkumar-sf**
Documentation update for non-global Interceptor

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [ ] API Documentation in code was updated
- [x] Documentation in [/docs/site](../tree/master/docs/site) was updated
- [ ] Affected artifact templates in `packages/cli` were updated
- [ ] Affected example projects in `examples/*` were updated

👉 [Check out how to submit a PR](https://loopback.io/doc/en/lb4/submitting_a_pr.html) 👈

### CODE REVIEW

**Comment by dhmlau** [comment]
@vaibhavkumar-sf, apologize about the typo. Yes, DCO is enough. However, the DCO checks failed.  
Is @vaibhavkumar-sf associated with `vaibhav.kumar@sourcefuse.com`?

**Comment by vaibhavkumar-sf** [comment]
@dhmlau  Yes, It's me .. Same ..

**Comment by dhmlau** [comment]
@vaibhavkumar-sf, it's working now! Let's wait for CI to run.

**Comment by vaibhavkumar-sf** [comment]
@dhmlau , should I change commit message scope from "doc" to "docs" as per log ? or it is fine ?
image

**Review by dhmlau — APPROVED** [review]

**Pull request merged**
